Repository sonata-project/SonataFormatterBundle, pull requests merged in 2018-05, with the labels that each got.

#332 Use renderWithExtraParams() instead of render()
  composer.json
  src/Controller/CkeditorAdminController.php
Labels: patch

#336 Add type hints
  UPGRADE-4.0.md
  composer.json
  src/Block/FormatterBlockService.php
  src/Controller/CkeditorAdminController.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataFormatterExtension.php
  src/Extension/BaseExtension.php
  src/Extension/BaseProxyExtension.php
  src/Extension/ControlFlowExtension.php
  src/Extension/ExtensionInterface.php
  src/Extension/GistExtension.php
  src/Form/EventListener/FormatterListener.php
  src/Form/Type/FormatterType.php
  src/Form/Type/SimpleFormatterType.php
  src/Formatter/BaseFormatter.php
  src/Formatter/FormatterInterface.php
  src/Formatter/MarkdownFormatter.php
  src/Formatter/Pool.php
  src/Formatter/RawFormatter.php
  src/Formatter/TextFormatter.php
  src/Formatter/TwigFormatter.php
  src/Twig/Extension/TextFormatterExtension.php
  src/Twig/Loader/LoaderSelector.php
  src/Twig/Node/GistNode.php
  src/Twig/SecurityPolicyContainerAware.php
  src/Twig/TokenParser/GistTokenParser.php
  src/Validator/Constraints/Formatter.php
Labels: major

#340 Improve style
  tests/Controller/CkeditorAdminControllerTest.php
  tests/Form/EventListener/FormatterListenerTest.php
  tests/Form/Type/FormatterTypeTest.php
  tests/Form/Type/SimpleFormatterTypeTest.php
  tests/Formatter/MarkdownFormatterTest.php
  tests/Formatter/PoolTest.php
  tests/Twig/Loader/LoaderSelectorTest.php
  tests/Validator/Constraints/FormatterValidatorTest.php
Labels: pedantic

#341 Fix ckeditor toolbar config
  src/Form/Type/FormatterType.php
  src/Form/Type/SimpleFormatterType.php
  src/Resources/config/form_fos.xml
  src/Resources/config/form_ivory.xml
  tests/Form/Type/FormatterTypeTest.php
Labels: patch

#342 Improve docs
  docs/index.rst
  docs/reference/ckeditor_medias.rst
  docs/reference/formatter_block.rst
  docs/reference/formatter_widget.rst
  docs/reference/installation.rst
  docs/reference/usage.rst
Labels: docs
