Repository sonata-project/SonataFormatterBundle, pull requests merged in 2021-09, with the labels that each got.

#603 Manual merge
  .php-cs-fixer.dist.php
  tests/Block/FormatterBlockServiceTest.php
  tests/DependencyInjection/SonataFormatterExtensionTest.php
  tests/Form/EventListener/FormatterListenerTest.php
  tests/Form/Type/FormatterTypeTest.php
  tests/Formatter/PoolTest.php
  tests/Formatter/TextFormatterTest.php
  tests/Resources/XliffTest.php
  tests/Twig/Loader/LoaderSelectorTest.php
  tests/Twig/SecurityPolicyContainerAwareTest.php
  tests/Validator/Constraints/FormatterTest.php
  tests/Validator/Constraints/FormatterValidatorTest.php
Labels: pedantic

#506 Add support for sonata-project/block-bundle 4.x
  composer.json
  src/Block/FormatterBlockService.php
  src/Resources/config/block.xml
  tests/Block/FormatterBlockServiceTest.php
Labels: minor

#607 Fix block di
  src/Resources/config/block.xml
Labels: bug

#615 Remove deprecated code
  src/Block/FormatterBlockService.php
Labels: major

#621 Update homepage
  composer.json
Labels: pedantic
