Repository sonata-project/SonataFormatterBundle, pull requests merged in 2023-04, with the labels that each got.

#749 Drop support for Symfony 4 and Twig 2
  .github/workflows/test.yaml
  composer.json
  src/Controller/CkeditorAdminController.php
  src/Resources/config/block.php
  src/Resources/config/form.php
  src/Resources/config/formatter.php
  src/Resources/config/media.php
  src/Resources/config/twig.php
  src/Resources/config/validators.php
  tests/App/AppKernel.php
  tests/App/config/config.yaml
  tests/App/config/config_symfony_v4.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/config_symfony_v6.yaml
  tests/App/config/services.php
  tests/Functional/Admin/CkeditorAdminTest.php
  tests/Functional/Admin/TextEntityAdminTest.php
Labels: minor

#751 DevKit updates for 5.x branch
  .github/workflows/auto-merge-dev-kit.yaml
  README.md
Labels: automerge

#752 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic
