Repository sonata-project/SonataFormatterBundle, pull requests merged in 2023-05, with the labels that each got.

#754 DevKit updates for 5.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
Labels: automerge, dev-kit

#756 Up rector to 0.16
  composer.json
Labels: pedantic

#757 DevKit updates for 5.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#759 Add support for form-extensions 2.0
  composer.json
Labels: minor

#760 Release 5.2.0
  CHANGELOG.md
Labels: dev-kit
