Repository sonata-project/SonataFormatterBundle, pull requests merged in 2024-06, with the labels that each got.

#795 Bump rector
  composer.json
Labels: pedantic

#796 DevKit updates
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#797 Solve internal class usage
  src/DependencyInjection/SonataFormatterExtension.php
Labels: patch
